module Main (main) where

import Advantages (advantages)
import Arguments (arguments)
import Artifacts (artifacts)
import BatchCalls (batchCalls)
import BatchedProtocol (batchedProtocol)
import Calls (calls)
import Checkpoints (checkpoints)
import Cohorts (cohorts)
import Collections (collections)
import Construction (construction)
import Control.Monad (unless)
import Dependencies (dependencies)
import Evaluation (evaluation)
import Evidence (evidence)
import Fixtures (fixtures)
import GroupedCalls (groupedCalls)
import Hedgehog (checkSequential)
import Inference (inference)
import InferenceObservations (inferenceObservations)
import Invocations (invocations)
import LearnerCalls (learnerCalls)
import Learning (learning)
import Literals (literals)
import Loads (loads)
import Loops (loops)
import Mismatches (mismatches)
import Numerical (numerical)
import NumericalProbes (numericalProbes)
import NumericalScores (numericalScores)
import Objectives (objectives)
import Observations (observations)
import Policies (policies)
import Probabilities (probabilities)
import Properties (properties)
import Quality (quality)
import Records (records)
import Reports (reports)
import ResidentCalls (residentCalls)
import ResidentDrivers (residentDrivers)
import ResidentObservations (residentObservations)
import Results (results)
import Rewards (rewards)
import Rollouts (rollouts)
import Schedules (schedules)
import ScoreProbes (scoreProbes)
import Scores (scores)
import Sessions (sessions)
import Store (store)
import System.Exit (exitFailure)
import Updates (updates)
import UseAdmission (useAdmission)
import UseBernstein (useBernstein)
import UseEvidence (useEvidence)
import UseGeneric (useGeneric)
import Uses (uses)
import Values (values)
import Workloads (workloads)

main :: IO ()
main = do
    outcomes <- traverse checkSequential [fixtures, properties, arguments, values, dependencies, evaluation, artifacts, construction, collections, records, literals, invocations, evidence, loads, store, checkpoints, inference, results, calls, batchCalls, groupedCalls, batchedProtocol, residentCalls, residentDrivers, residentObservations, rewards, cohorts, rollouts, sessions, learning, advantages, objectives, mismatches, updates, learnerCalls, loops, schedules, policies, probabilities, workloads, reports, quality, observations, inferenceObservations, numerical, scores, scoreProbes, numericalScores, numericalProbes, uses, useEvidence, useAdmission, useBernstein, useGeneric]
    unless (and outcomes) exitFailure
